language: go
sudo: false

matrix:
  include:
    - go: 1.13.x

install: true

notifications:
  email: false

addons:
  mariadb: '10.4'

services: mariadb

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f)
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls
  - go get github.com/rakyll/gotest
  - sudo mysql -e 'CREATE DATABASE goyave CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
  - sudo mysql -e 'CREATE USER "goyave"@"%" IDENTIFIED BY "secret"'
  - sudo mysql -e 'GRANT ALL PRIVILEGES ON goyave.* TO "goyave"@"%"'

script:
  - gotest -race -count=20 .
  - gotest -v -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... ./...
  - goveralls -coverprofile coverage.txt -service=travis-ci
  - golint -set_exit_status $(go list ./...)
