language: go
sudo: false

matrix:
  include:
    - go: 1.13.x
    - go: tip

install: true

notifications:
  email: false

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... ./...
  - goveralls -coverprofile coverage.txt -service=travis-ci
  - golint -set_exit_status $(go list ./...)
